# Outline {visibility="uncounted"}
<!-- ###################################################################### -->

## Current Research (approx. **30 minutes**) {auto-animate=true visibility="uncounted"}

* Introduction -- Theme: **Robustness** - both control and measurement! (~**5 minutes**)
    * Challenges in robotic manipulation: all challenges in one go
        * Modeling :left_right_arrow: Sensing :arrow_right: Control Synthesis :arrow_right: Robustness :arrow_right: Performance :arrow_down:
        * Iteration  
    * Basic comparison between our approach and the typical literature
        * Factor graphs for GTSAM + OrbSlam + EM field integration
        * Data-driven Controller Synthesis: basic overview, no details!

* EM Sensing with GTSAM (~**10 minutes**)
    * Difficulties with relative pose sensing
    * Three-phase power line geometry 
    * Lack of any good state-of-the-art method
    * Our method based on gradient of the total electromagnetic field strength


## Current Research (approx. **30 minutes**) {auto-animate=true visibility="uncounted"}

* EM Sensing with GTSAM (~**10 minutes**)
    * Difficulties with relative pose sensing
    * Three-phase power line geometry 
    * Lack of any good state-of-the-art method
    * Our method based on gradient of the total electromagnetic field strength

* Passivity-Based Data-Driven Controller Synthesis (~**15 minutes**)
    * Brief PBC design motivation
    * NeuralPBC explanation - add training procedure here.
    * Current manipulation results (EAGER project)
    * Current drone-line manipulation results


## Research Agenda (approx. **10 minutes**) {auto-animate=true visibility="uncounted"}

* Vision (~**2 minutes**)
    * Service robotics needs robust low-level controllers
    * Drones / AGVs need robust sensing and controllers to perform dangerous tasks.
    * In 10 years, data-driven synthesis methods will have matured and made robust.

* Future Techniques (~**6 minutes**)
    * Robustness of GNN-based controllers
    * Convex Optimization Layers and ADMM on GNNs
    * Transfer learning to multiple domains (few-shot performance)
        * Guiding controller synthesis with human-imitation using LLMs
        * Representation learning

* Potential Funding Mechanisms (~**2 minutes**)
    * NSF: Foundational Research in Robotics
    * SBIR / STTR: Currently with Pitch Aeronautics, explore local companies
    * NIH: Retain and expand biomedical collaboration with BSU / UTD faculty